/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package spark.project
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext

object App {
  def main(args: Array[String]): Unit = {

    // val spark = SparkSession.builder.appName("SimpleApp").getOrCreate()

    val version = SparkContext.version
    print(version)
    
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
